### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


PUNTO 1: CREA UN NUOVO VETTORE CON TUTTI I NUMERI PRIMI TRA 0 E 20


In [28]:

import numpy as np

# Creo un nuovo vettore
numeri_primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])

# Stampo il vettore
print(numeri_primi)

[ 2  3  5  7 11 13 17 19]


PUNTO 2: SELEZIONARE TUTTE LE VOCI DEL VETTORE MAGGIORE DI 10


In [29]:

# Seleziono tutte le voci maggiori di 10
maggiori_di_10 = numeri_primi[numeri_primi > 10]

# Stampo il risultato
print(maggiori_di_10)

[11 13 17 19]


PUNTO 3: SELEZIONARE TUTTI I NUMERI PRIMI DELLA LISTA

In [30]:


# Seleziono tutti i numeri primi
primi_pari = numeri_primi[numeri_primi == 2]

# Stampo il risultato
print(primi_pari)

[2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [31]:
import numpy as np

# Creo un array 2D
a = np.random.randint(1, 10, (5, 5))    # Array 5x5 con numeri casuali tra 1 e 10 

# Creo b, contenente la 2° e 3° riga
b = a[[1, 3], :]                        # Le righe 2 (indice 1) e 4 (indice 3)

# Creo c, contenente solo la 3° riga
c = a[2, :]                             # La riga 3 (indice 2)

# Divido ogni colonna dell'array a con l'array c
diviso = a / c                          # Ogni elemento della riga a diviso il corrispondente elemnto di c

# Stampo i risultati
print("Array a:\n", a)
print("\nArray b (2ª e 4ª riga):\n", b)
print("\nArray c (3ª riga):\n", c)
print("\nArray diviso (ogni colonna di a divisa per c):\n", diviso)

Array a:
 [[4 7 9 1 9]
 [7 8 9 7 9]
 [1 9 3 7 6]
 [4 7 3 7 9]
 [9 9 7 3 6]]

Array b (2ª e 4ª riga):
 [[7 8 9 7 9]
 [4 7 3 7 9]]

Array c (3ª riga):
 [1 9 3 7 6]

Array diviso (ogni colonna di a divisa per c):
 [[4.         0.77777778 3.         0.14285714 1.5       ]
 [7.         0.88888889 3.         1.         1.5       ]
 [1.         1.         1.         1.         1.        ]
 [4.         0.77777778 1.         1.         1.5       ]
 [9.         1.         2.33333333 0.42857143 1.        ]]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [32]:
import numpy as np

## 1. Creo un array 10x3 con numeri casuali nell'intervallo [0, 1]
array = np.random.rand(10, 3)

## 2. Seleziono il numero più vicino a 0.5 per ogni riga
numero_piu_vicino = np.abs(array - 0.5)                 # Calcola la differenza assoluta da 0.5
indice_minimo = np.argmin(numero_piu_vicino, axis=1)    # Trovo l'indice con  la differenza minima

# Utilizzo l'indice per selezionare il valore più vicino a 0.5
valori_piu_vicini = array[np.arange(array.shape[0]), indice_minimo]

# Stampo il risultato
print("Array:\n", array)
print("\nValori più vicini a 0.5 per ogni riga:\n", valori_piu_vicini)

Array:
 [[0.83103071 0.72947173 0.77392348]
 [0.8837372  0.33804682 0.29175168]
 [0.16200066 0.8488153  0.23249843]
 [0.42824231 0.04042379 0.075137  ]
 [0.56400406 0.26825657 0.08698369]
 [0.96889858 0.16724227 0.07860442]
 [0.98709646 0.66972868 0.99680777]
 [0.12134448 0.91802187 0.55670784]
 [0.92556546 0.78034163 0.63277603]
 [0.41316467 0.61956465 0.57187955]]

Valori più vicini a 0.5 per ogni riga:
 [0.72947173 0.33804682 0.23249843 0.42824231 0.56400406 0.16724227
 0.66972868 0.55670784 0.63277603 0.57187955]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


PUNTO 1: INSERISCO I VALORI DELLA FREQUENZA CARDIACA IN UN ARRAY NUMPY.

In [33]:
import numpy as np

# Frequenze cardiache registrate
frequenze_cardiache = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

# Stampo l'array
print("Frequenze cardiache registrata durante la giornata:")
print(frequenze_cardiache)

Frequenze cardiache registrata durante la giornata:
[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]


PUNTO 2: TROVA LA FREQUENZA CARDIACA MINIMA


In [34]:
# Frequenza cardiaca minima
frequenza_minima = np.min(frequenze_cardiache)

# Stampo il risultato
print("Frequenza cardiaca minima:", frequenza_minima)

Frequenza cardiaca minima: 60


PUNTO 3: TROVA LA FREQUENZA CARDIACA MASSIMA


In [35]:
# Frequenza cardiaca massima
frequenza_massima = np.max(frequenze_cardiache)

# Stampo il risultato
print("Frequenza cardiaca massima:", frequenza_massima)

Frequenza cardiaca massima: 164


PUNTO 4: CALCOLA LA PERCENTUALE DI LETTURE EFFETTUATE MENTRE STAVI FACENDO ESERCIZIO FISICO.


In [36]:
# Creo un array con True se la frequenza è maggiore di 120, altrimenti False
esercizio = frequenze_cardiache > 120

# CalcoLo la percentuale di letture durante l'esercizio fisico
percentuale_esercizio = np.mean(esercizio) * 100  # Media dei True (percentuale)

# Stampo il risultato
print(f"Percentuale di letture durante l'esercizio fisico: {percentuale_esercizio:.2f}%")

Percentuale di letture durante l'esercizio fisico: 52.38%


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


PUNTO 1: CREARE UN VETTORE CON GLI STIPENDI E CALCOLARE IL COSTO TOTALE DEL PERSONALE


In [37]:
import numpy as np

# Creo il vettore degli stipendi
stipendi = np.array ([50000, 105250, 55000, 89000]) 

# Calcolo il costo totale del personale
costo_totale = np.sum (stipendi)

# Stampo il risultato
print("Costo del personale:", costo_totale)

Costo del personale: 299250


PUNTO 2: AUMENTO DEL 15% PER IL CEO


In [38]:
# Aumento del 15% per il CEO (Indice 3 = 105250)
stipendi[1] = stipendi[1] * 1.15

# Stampo il nuovo vettore
print("Nuovo vettore degli stipendi dopo l'aumento del CEO:", stipendi)

Nuovo vettore degli stipendi dopo l'aumento del CEO: [ 50000 121037  55000  89000]


PUNTO 3: VERIFICA SE IL NUOVO STIPENDIO DEL CEO E' 121.037,50 $.

In [39]:
# Verifico lo stipendio del CEO
stipendio_ceo = stipendi[1]

# Stampo il nuovo valore
print("Stipendio del CEO:", stipendio_ceo)

# RISPOSTA: Il motivo per cui il valore potrebbe non essere esattamente uguale a 121.037,50 $ è dovuto alle 
#           imprecisioni della rappresentazione in virgola mobile, in quanto Pythoon usa un linguaggio in floating point.

Stipendio del CEO: 121037


PUNTO 4: CREARE IL VETTORE UTILIZZANDO DTYPE PER OTTENERE UNO STIPENDIO ESATTO DI 121.037,50 DOLLARI

In [40]:
# Creo il vettore con dtype float64
stipendi = np.array([50000, 105250, 55000, 89000], dtype=np.float64)

# Applico l'aumento del 15% per il CEO
stipendi[1] = stipendi[1] * 1.15

# Stampo il nuovo vettore con maggiore precisione
print("Vettore con dtype float64:", stipendi)

## INFO: Per ottenere esattamente 121.037,50 $, posso forzare il tipo di dato del vettore a float64, che ha una maggiore precisione.

Vettore con dtype float64: [ 50000.  121037.5  55000.   89000. ]


PUNTO 5: AUMENTO DEL 20 % PER L'IMPIEGATA CON LO STIPENDIO PIU' BASSO

In [41]:
# Aumento del 20 % per l'impiegata (Indice 0 = 50.000 $)
stipendi[0] = stipendi[0] * 1.20

# Stampo il nuovo vettore
print("Vettore dopo l'aumento dell'impiegata:", stipendi)

Vettore dopo l'aumento dell'impiegata: [ 60000.  121037.5  55000.   89000. ]


PUNTO 6: AUMENTO DEL 10 % PER GLI ALTRI DUE DIPENDENTI

In [42]:
# Aumento del 10 % per i due dipendenti (Indice 2 = 55.000 $   e   Indice 3 = 89.000 $)
stipendi[2] = stipendi[2] * 1.10
stipendi[3] = stipendi[3] * 1.10

# Stampo il nuovo vettore
print("Vettore dopo l'aumento degli altri dipendenti:", stipendi)

Vettore dopo l'aumento degli altri dipendenti: [ 60000.  121037.5  60500.   97900. ]


PUNTO 7: CALCOLARE IL COSTO TOTALE DEL PERSONALE DOPO GLI AUMENTI E L'AUMENTO DI 16.000 $ DEL CEO.

In [43]:
# Utilizzo il vettore esistente degli stipendi
stipendi = np.array([50000, 105250, 55000, 89000], dtype=np.float64)

# Aumento del 15% per il CEO
stipendi[1] = stipendi[1] * 1.15

# Aumento del 20% per l'impiegata con lo stipendio più basso
stipendi[0] = stipendi[0] * 1.20

# Aumento del 10% per gli altri due dipendenti
stipendi[2] = stipendi[2] * 1.10
stipendi[3] = stipendi[3] * 1.10

# Calcolo il costo totale del personale dopo gli aumenti
costo_totale_aggiornato = np.sum(stipendi)

# Calcolo l'aumento del CEO (arrotondato a due decimali)
aumento_ceo = round(stipendi[1] - 105250, 2)

# Stampo i risultati
print("Costo totale del personale dopo gli aumenti:", round(costo_totale_aggiornato, 2))
print("Aumento del CEO:", aumento_ceo)

## INFO: round(): Serve per arrotondare correttamente i valori a due decimali


Costo totale del personale dopo gli aumenti: 339437.5
Aumento del CEO: 15787.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

CODICE PER GENERARE E SALVARE I DATI

In [44]:
import numpy as np

# Generazione di 200 valori casuali di emissioni di CO2 in tonnellate per anno tra 4 e 20
co2_emissioni = np.round(np.random.uniform(4, 20, 200), 2)

# Nome del file di output
output_file = "emissioni.txt"  # Salva il file nella cartella di lavoro corrente

# Salvataggio dei dati su file
np.savetxt(output_file, co2_emissioni, fmt="%.2f")

# Restituisco il percorso del file
print(f"File salvato in: {output_file}")

File salvato in: emissioni.txt


PUNTO 1: CARICA IL FILE DELLE EMISSIONI DI CO2

In [45]:
import numpy as np

# Carico il file delle emissioni di CO2
co2_data = np.loadtxt('emissioni.txt')

# Verifico che i dati siano stati caricati correttamente
print(co2_data[:10])        # Stampo i primi 10 valori per verificare

[ 4.38 13.73 10.86 19.87  7.07  8.99 16.26 18.58  7.1  19.25]


PUNTO 2: CALCOLA QUANTI VALORI DI CO2 SONO SOPRA LA SOGLIA DI 18 TONNELLATE PER ANNO E IL LORO VALORE MEDIO

In [46]:
# Soglia di 18 tonnellate
soglia = 18

# Filtro i valori sopra la soglia
co2_sopra_soglia = co2_data[co2_data > soglia]

# Calcolo quanti valori sono sopra la soglia
num_valori_sopra_soglia = len(co2_sopra_soglia)

# Calcolo la media delle emissioni sopra la soglia
media_sopra_soglia = np.mean(co2_sopra_soglia)

# Stampo i risultati
print(f"Numero di valori sopra la soglia di {soglia} tonnellate: {num_valori_sopra_soglia}")
print(f"Valore medio delle emissioni sopra la soglia: {media_sopra_soglia}")

Numero di valori sopra la soglia di 18 tonnellate: 31
Valore medio delle emissioni sopra la soglia: 19.022580645161288


PUNTO 3: CALCOLARE LA FRAZIONE TOTALE DI EMISSIONI SOPRA LA SOGLIA

In [47]:
# Somma totale di tutte le emissioni
somma_totale = np.sum(co2_data)

# Somma delle emissioni sopra la soglia
somma_sopra_soglia = np.sum(co2_sopra_soglia)

# Calcolo la frazione
frazione_sopra_soglia = somma_sopra_soglia / somma_totale

# Stampo la frazione
print(f"Frazione totale di emissioni sopra la soglia: {frazione_sopra_soglia:.4f}")

## INFO: Frazione totale = somma totale sopra la soglia/somma totale

Frazione totale di emissioni sopra la soglia: 0.2351


### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


PUNTO 1: SELEZIONARE GLI INTERVISTATI CON ALMENO 12 ANNI DI ISTRUZIONE

In [48]:
import numpy as np

# Matrice survey
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

# Seleziono gli intervistati con almeno 12 anni di istruzione
intervistati_12_anni = survey_matrix[survey_matrix[:, 2] >= 12]

# Stampo i risultati
print("Intervistati con almeno 12 anni di istruzione:")
print(intervistati_12_anni)


## INFO: In questo caso, voglio selezionare solo le righe della matrice in cui 
#        l'elemento nella terza colonna (che rappresenta gli anni di istruzione) è maggiore o uguale a 12.

Intervistati con almeno 12 anni di istruzione:
[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]


PUNTO 2: SELEZIONARE SOLO IL REDDITO DEGLI INTERVISTATI CON ALMENO 12 ANNI DI ISTRUZIONE

In [49]:
# Seleziono i redditi degli intervistati con almeno 12 anni di istruzione
redditi_12_anni = survey_matrix[survey_matrix[:, 2] >= 12, 1]

# Stampo i risultati
print("Redditi degli intervistati con almeno 12 anni di istruzione:")
print(redditi_12_anni)

## INFO: Simile al precedente , ma in questo caso seleziono solo la colonna corrispondente al reddito (2°)

Redditi degli intervistati con almeno 12 anni di istruzione:
[52000 63000 58000]


PUNTO 3: CALCOLARE IL REDDITO MEDIO DEGLI INTERVISTATI CON ALMENO 12 ANNI DI ISTRUZIONE

In [50]:
# Calcolo il reddito medio (a 2 cifre decimali)
reddito_medio_12_anni = round(np.mean(redditi_12_anni), 2)

# Stampo il risultato
print(f"Reddito medio degli intervistati con almeno 12 anni di istruzione: {reddito_medio_12_anni}")

Reddito medio degli intervistati con almeno 12 anni di istruzione: 57666.67


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [51]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

In [52]:
import numpy as np

# Dati dell'età
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90, 55, 55, 96, 109,  82, 55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

# 1. Rimuovo i valori errati (999)
valid_ages = ages[ages != 999]

# 2. Determino l'età del cittadino più anziano
oldest_age = np.max(valid_ages)

# Stampo i risultati
print(f"L'età del cittadino più anziano è: {oldest_age}")


L'età del cittadino più anziano è: 112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [53]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]



Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."

In [54]:
import random

# Lista di parole
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

# Estrazione casuale di 5 parole con reinserimento
parole_estratte = random.choices(lista_parole, k=5)

# Frase con gli spazi vuoti e newline (\n) per andare a capo
frase = f"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {parole_estratte[0]} che proteggeva.\n"
frase += f"Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante\n"
frase += f"e le offrì il {parole_estratte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, \"{parole_estratte[2]}\".\n"
frase += f"Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parole_estratte[3]}.\n"
frase += f"Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.\n"
frase += f"Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:\n"
frase += f"\"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parole_estratte[4]}!\"\n"
frase += "Ci fu grande gioia e celebrazione."

# Stampa della frase completa
print(frase)


In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico PARENTE che proteggeva.
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante
e le offrì il IMPERO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "BATTERIA".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un COPERTA.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza ATTEGGIAMENTO!"
Ci fu grande gioia e celebrazione.
